// ─────────────────────────────────────────────────────────────────────────────
// Disposable / temporary email domain blocklist (B27, 2026-04-30)
// ─────────────────────────────────────────────────────────────────────────────
//
// Why we block these domains:
//   The B23 email-verify gate (POST /auth/login returns 403 if
//   users.email_verified is false) is built on the assumption that the
//   inbox owner is a real human who controls the address. Disposable
//   services break that assumption in two ways:
//
//     1. PUBLIC inbox services (mailinator.com, yopmail.com, getnada.com)
//        — anyone who guesses the local-part can read the OTP and "verify"
//        the account. Email verification becomes meaningless.
//     2. EPHEMERAL inbox services (10minutemail.com, guerrillamail.com,
//        tempmail.org) — the inbox self-destructs after 10–60 minutes,
//        so even though THE attacker controlled it briefly, the account
//        becomes orphaned (no recoverable address). Bad for support,
//        bad for KYC, and the natural attacker pattern for sybil/abuse.
//
//   Both classes enable cheap, unlimited account creation that bypasses
//   our captcha + IP rate limits + behaviour-timing gates because each
//   signup is from a fresh "real-looking" identity.
//
// Curated list rationale:
//   ~120 domains covering the most common services + their alias
//   domains. We deliberately stop short of an exhaustive 3,000+ entry
//   list (e.g. github.com/disposable-email-domains/disposable-email-domains)
//   because:
//     - 95%+ of casual disposable signup traffic uses the top ~50 services.
//     - A static list compiled into the bundle is deterministic, has zero
//       network/fetch risk, and is trivial to audit in PR review.
//     - New services can be appended in one line.
//
// Sources cross-referenced (all public):
//   - github.com/disposable-email-domains/disposable-email-domains
//   - github.com/disposable/disposable-email-domains
//   - github.com/wesbos/burner-email-providers
//   - manual review of top SEO results for "temp mail" / "10 minute mail"
//
// All entries are lowercased. The check is performed AFTER B24 email
// normalization (toLowerCase().trim()), so case-only variants are
// already canonicalized before we look them up.

export const DISPOSABLE_EMAIL_DOMAINS: ReadonlySet<string> = new Set([
  // ── Mailinator family (PUBLIC inboxes — biggest single offender) ──
  "mailinator.com",
  "mailinator.net",
  "mailinator.org",
  "mailinator2.com",
  "mailinater.com",
  "suremail.info",
  "asdasd.ru",
  "sogetthis.com",
  "binkmail.com",
  "spamherelots.com",
  "spamhereplease.com",
  "thisisnotmyrealemail.com",

  // ── 10MinuteMail family (EPHEMERAL — self-destructs) ──
  "10minutemail.com",
  "10minutemail.net",
  "10minutemail.org",
  "10minutemail.co.uk",
  "10minutemail.de",
  "10minutemail.us",
  "10minemail.com",
  "10minutesmail.com",
  "10minutesmail.net",

  // ── GuerrillaMail family ──
  "guerrillamail.com",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamail.biz",
  "guerrillamail.de",
  "guerrillamailblock.com",
  "sharklasers.com",
  "grr.la",
  "spam4.me",
  "pokemail.net",

  // ── Yopmail family ──
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "yopmail.org",
  "cool.fr.nf",
  "courriel.fr.nf",
  "jetable.fr.nf",
  "nospam.ze.tc",
  "nomail.xl.cx",
  "mega.zik.dj",
  "speed.1s.fr",

  // ── Temp-mail / TempMail family ──
  "temp-mail.org",
  "temp-mail.io",
  "temp-mail.ru",
  "tempmail.com",
  "tempmail.net",
  "tempmail.email",
  "tempmail.de",
  "tempmail.dev",
  "tempmailaddress.com",
  "tempinbox.com",
  "tempmail.plus",

  // ── Throwaway-style ──
  "throwawaymail.com",
  "throwam.com",
  "trashmail.com",
  "trashmail.net",
  "trashmail.de",
  "trashmail.ws",
  "trashmail.io",
  "wegwerfemail.de",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",

  // ── Maildrop / Getnada / Moakt / Mintemail ──
  "maildrop.cc",
  "getnada.com",
  "nada.email",
  "moakt.com",
  "moakt.cc",
  "moakt.ws",
  "mailcatch.com",
  "mintemail.com",
  "emailondeck.com",
  "fakeinbox.com",
  "fakemail.net",
  "fakemailgenerator.com",
  "spambox.us",
  "spambox.me",

  // ── Burner / Disposable ──
  "burnermail.io",
  "dispostable.com",
  "disposable.com",
  "deadaddress.com",
  "dropmail.me",
  "mvrht.com",
  "spamavert.com",
  "spamgourmet.com",
  "instantemailaddress.com",
  "instant-mail.de",

  // ── AirMail / Getairmail / Inbox-style ──
  "getairmail.com",
  "airmail.cc",
  "inboxbear.com",
  "inboxalias.com",
  "incognitomail.com",
  "incognitomail.net",
  "incognitomail.org",

  // ── Mohmal / Linshi / Tmail / Mytemp ──
  "mohmal.com",
  "mohmal.in",
  "mohmal.tech",
  "linshiyou.com",
  "linshi-email.com",
  "tmail.io",
  "tmailweb.com",
  "tmail.ws",
  "mytemp.email",
  "mytrashmail.com",
  "mt2014.com",

  // ── EmailFake / EmailTemporanea / 33mail ──
  "emailfake.com",
  "emailtemporanea.com",
  "emailtemporanea.net",
  "33mail.com",
  "armyspy.com",
  "cuvox.de",
  "dayrep.com",
  "einrot.com",
  "fleckens.hu",
  "gustr.com",
  "jourrapide.com",
  "rhyta.com",
  "superrito.com",
  "teleworm.us",

  // ── Cock.li family (often abused by spammers) ──
  "cock.li",
  "cock.lu",
  "cock.email",
  "horsefucker.org",
  "national.shitposting.agency",

  // ── Misc commonly seen in spam signups ──
  "jetable.org",
  "jetable.net",
  "spamfree24.com",
  "spamfree24.de",
  "spamfree24.eu",
  "spamfree24.info",
  "spamfree24.net",
  "spamfree24.org",
  "byom.de",
  "tempemail.com",
  "tempemail.net",
  "tempinbox.co.uk",
  "tempr.email",
  "discard.email",
  "discardmail.com",
  "discardmail.de",
  "harakirimail.com",
  "haltospam.com",
  "trbvm.com",
  "spamspot.com",
  "spamstack.net",
  "thankyou2010.com",
  "trashymail.com",
  "ubismail.net",
  "vpn.st",
  "vsimcard.com",
  "wuzup.net",
  "yapped.net",
  "yourdomain.com",
  "zoaxe.com",
  "zoemail.org",

  // ── B27.1 expansion (2026-04-30) ──────────────────────────────────────
  // Caught during prod n2n test — 4 well-known services that were missing
  // from the original B27 list. Plus aggressive coverage of ~60 more
  // common services that show up in practical spam signups.

  // 1secmail family (popular open-API service)
  "1secmail.com",
  "1secmail.net",
  "1secmail.org",
  "1secmail.xyz",

  // Mailnesia
  "mailnesia.com",

  // Spambog family
  "spambog.com",
  "spambog.de",
  "spambog.net",
  "spambog.ru",

  // Tempr (dot-io variant — original list had tempr.email)
  "tempr.io",

  // Mail.tm family (very popular open-API disposable)
  "mail.tm",
  "mailtm.cc",

  // Inboxkitten / Mailpoof / Crazymailing
  "inboxkitten.com",
  "mailpoof.com",
  "crazymailing.com",

  // Email-fake / Tempmailo / Generator.email
  "email-fake.com",
  "tempmailo.com",
  "generator.email",
  "etmail.com",
  "etmaill.com",

  // Smailpro / Tempm / Tempmailbox / Maildim
  "smailpro.com",
  "tempm.com",
  "tempmailbox.net",
  "maildim.com",
  "mailde.com",
  "post-shift.fr",
  "snapmail.cc",
  "vnedu.me",

  // 0-* and number-prefixed
  "0-mail.com",
  "0clickemail.com",
  "0wnd.net",
  "0wnd.org",
  "10mail.org",
  "10minute-email.com",
  "10minutemail.cf",
  "10minutemail.ga",
  "10minutemail.ml",
  "20minutemail.com",
  "20minutemail.it",
  "30minutemail.com",
  "30wave.com",
  "60minutemail.com",
  "75hosting.com",
  "75hosting.net",
  "75hosting.org",
  "99experts.com",

  // Anonbox / Anonymbox / Anonymous-ish
  "anonbox.net",
  "anonymbox.com",
  "anonmails.de",
  "anonymousmail.org",
  "anyalias.com",
  "asorent.com",

  // More mailinator aliases (the org runs ~30 alias domains)
  "letthemeatspam.com",
  "veryrealemail.com",
  "reallymymail.com",
  "spamthisplease.com",
  "sendspamhere.com",
  "stuffmail.de",
  "thelimestones.com",
  "tradermail.info",
  "tropicalbass.info",
  "veryrealemail.com",
  "tittbit.in",
  "objectmail.com",

  // More yopmail aliases
  "yopmail.gq",
  "yopmail.tk",
  "yopmail.ml",
  "yopmail.cf",
  "yopmail.ga",

  // More guerrillamail aliases
  "guerrillamail.info",
  "guerrillamailblock.com",
  "spam.la",
  "spam.su",
  "spamday.com",
  "spamhole.com",
  "spammotel.com",
  "spamthis.co.uk",
  "spamthisplease.com",

  // Mintvine, Mintemail variants
  "mintemail.com",

  // Other commonly cited services
  "anit.ro",
  "armail.in",
  "bloatbox.com",
  "boxformail.in",
  "bsnow.net",
  "bspamfree.org",
  "bugmenot.com",
  "buyusedlibrarybooks.org",
  "cachedot.net",
  "cellurl.com",
  "chammy.info",
  "chickenkiller.com",
  "chong-mail.com",
  "chong-mail.net",
  "chong-mail.org",
  "clixser.com",
  "cmail.club",
  "cmail.com",
  "consumerriot.com",
  "cosmorph.com",
  "courriel.fr.nf",
  "courrieltemporaire.com",
  "crapmail.org",
  "cuvox.de",
  "deadchildren.org",
  "deadfake.cf",
  "deadfake.ga",
  "deadfake.ml",
  "deadfake.tk",
  "delikkt.de",
  "devnullmail.com",
  "dharmatel.net",
  "dingbone.com",
  "discardmail.com",
  "discardmail.de",
  "disposeamail.com",
  "disposemail.com",
  "dispomail.eu",
  "dispostable.com",
  "dodgeit.com",
  "dodgit.com",
  "dodgit.org",
  "donemail.ru",
  "dontreg.com",
  "dontsendmespam.de",
  "dotmsg.com",
  "dump-email.info",
  "dumpandjunk.com",
  "duskmail.com",
  "easytrashmail.com",
  "edv.to",
  "einmalmail.de",
  "emaildienst.de",
  "emailgo.de",
  "emailias.com",
  "emailigo.de",
  "emailinfive.com",
  "emaillime.com",
  "emailmiser.com",
  "emailproxsy.com",
  "emailsensei.com",
  "emailspam.cf",
  "emailspam.ga",
  "emailspam.gq",
  "emailspam.ml",
  "emailspam.tk",
  "emailtemporario.com.br",
  "emailthe.net",
  "emailtmp.com",
  "emailto.de",
  "emailwarden.com",
  "emailx.at.hm",
  "emailxfer.com",
  "emailz.cf",
  "emailz.ga",
  "emailz.gq",
  "emailz.ml",
  "emeil.in",
  "emeil.ir",
  "emz.net",
  "evopo.com",
  "explodemail.com",
  "express.net.ua",
  "facebook-email.cf",
  "facebook-email.ga",
  "facebook-email.ml",
  "fakeinbox.cf",
  "fakeinbox.ga",
  "fakeinbox.ml",
  "fakeinbox.tk",
  "fakeinformation.com",
  "fammix.com",
  "fansworldwide.de",
  "fantasymail.de",
  "fastacura.com",
  "fastchevy.com",
  "fastchrysler.com",
  "fastkawasaki.com",
  "fastmazda.com",
  "fastmitsubishi.com",
  "fastnissan.com",
  "fastsubaru.com",
  "fastsuzuki.com",
  "fasttoyota.com",
  "fastyamaha.com",
  "fightallspam.com",
  "filzmail.com",
  "fizmail.com",
  "fr33mail.info",
  "frapmail.com",
  "friendlymail.co.uk",
  "fux0ringduh.com",
  "garliclife.com",
  "gehensiemirnichtaufdensack.de",
  "get1mail.com",
  "get2mail.fr",
  "getairmail.cf",
  "getairmail.ga",
  "getairmail.gq",
  "getairmail.ml",
  "getairmail.tk",
  "getmails.eu",
  "getonemail.com",
  "getonemail.net",
  "ghosttexter.de",
  "girlsundertheinfluence.com",
  "gishpuppy.com",
  "gomail.in",
  "gotmail.net",
  "gotmail.org",
  "gowikibooks.com",
  "gowikicampus.com",
  "gowikicars.com",
  "gowikifilms.com",
  "gowikigames.com",
  "gowikimusic.com",
  "gowikinetwork.com",
  "gowikitravel.com",
  "gowikitv.com",
  "great-host.in",
  "greensloth.com",
  "gsrv.co.uk",
  "guerillamail.biz",
  "guerillamail.com",
  "guerillamail.de",
  "guerillamail.info",
  "guerillamail.net",
  "guerillamail.org",
  "h.mintemail.com",
  "h8s.org",
  "hatespam.org",
  "headstrong.de",
  "herp.in",
  "hidemail.de",
  "hidzz.com",
  "hmamail.com",
  "hochsitze.com",
  // ⚠ hotpop.com REMOVED — was a legitimate free email provider.
  "hulapla.de",
  "ieatspam.eu",
  "ieatspam.info",
  "ieh-mail.de",
  "ihazspam.ca",
  "imails.info",
  "inboxalias.com",
  "inboxclean.com",
  "inboxclean.org",
  "incognitomail.com",
  "incognitomail.net",
  "incognitomail.org",
  "ipoo.org",
  "irish2me.com",
  "iwi.net",
  "jnxjn.com",
  "junk1e.com",
  "kasmail.com",
  "kaspop.com",
  "keepmymail.com",
  "killmail.com",
  "killmail.net",
  "klassmaster.com",
  "klzlk.com",
  "kulturbetrieb.info",
  "kurzepost.de",
  "lawlita.com",
  "letthemeatspam.com",
  "lhsdv.com",
  "lifebyfood.com",
  "litedrop.com",
  "loadby.us",
  "login-email.cf",
  "login-email.ga",
  "login-email.ml",
  "login-email.tk",
  "lookugly.com",
  "lopl.co.cc",
  "lortemail.dk",
  "lr78.com",
  "lroid.com",
  "m4ilweb.info",
  "mailbidon.com",
  "mailbiz.biz",
  "mailblocks.com",
  "mailbucket.org",
  "mailcat.biz",
  "mailde.de",
  "mailde.info",
  "maileater.com",
  "maileimer.de",
  "mailexpire.com",
  "mailfa.tk",
  "mailforspam.com",
  "mailfreeonline.com",
  "mailguard.me",
  "mailimate.com",
  "mailin8r.com",
  "mailme.lv",
  "mailme24.com",
  "mailmoat.com",
  "mailms.com",
  "mailnator.com",
  "mailnull.com",
  "mailproxsy.com",
  "mailquack.com",
  "mailrock.biz",
  "mailscrap.com",
  "mailshell.com",
  "mailsiphon.com",
  "mailslapping.com",
  "mailtemp.info",
  "mailtome.de",
  "mailtothis.com",
  "mailtrash.net",
  "mailtv.net",
  "mailtv.tv",
  "mailzilla.com",
  "makemetheking.com",
  "manybrain.com",
  "mbx.cc",
  "mega.zik.dj",
  "meinspamschutz.de",
  "meltmail.com",
  "messagebeamer.de",
  "mierdamail.com",
  "mintemail.com",
  "misterpinball.de",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",
  "msa.minsmail.com",
  "mt2009.com",
  "mt2014.com",
  "mt2015.com",
  "mycard.net.ua",
  "mycleaninbox.net",
  "myemailboxy.com",
  "mymail-in.net",
  "mypacks.net",
  "mypartyclip.de",
  "myphantomemail.com",
  "myspaceinc.com",
  "myspaceinc.net",
  "myspaceinc.org",
  "myspacepimpedup.com",
  "myspamless.com",
  "mytemp.email",
  "mytempemail.com",
  "mytempmail.com",
  "mytrashmail.com",
  "neomailbox.com",
  "nepwk.com",
  "nervmich.net",
  "nervtmich.net",
  "netmails.com",
  "netmails.net",
  "netzidiot.de",
  "neverbox.com",
  "nice-4u.com",
  "no-spam.ws",
  "noblepioneer.com",
  "nomail.pw",
  "nomail.xl.cx",
  "nomail2me.com",
  "noref.in",
  "nospam.ze.tc",
  "nospam4.us",
  "nospamfor.us",
  "nospamthanks.info",
  "notmailinator.com",
  "nowhere.org",
  "nowmymail.com",
  "nurfuerspam.de",
  // ⚠ nus.edu.sg REMOVED — National University of Singapore real EDU domain.
  "objectmail.com",
  "obobbo.com",
  "odnorazovoe.ru",
  "one-time.email",
  "oneoffemail.com",
  "onewaymail.com",
  "online.ms",
  "oopi.org",
  "opayq.com",
  "ordinaryamerican.net",
  "otherinbox.com",
  "ourklips.com",
  "outlawspam.com",
  "ovpn.to",
  "owlpic.com",
  "pancakemail.com",
  "pcusers.otherinbox.com",
  "pjjkp.com",
  "plexolan.de",
  // ⚠ poczta.onet.pl REMOVED — legitimate Polish email provider (Onet).
  "politikerclub.de",
  "poofy.org",
  "pookmail.com",
  "privacy.net",
  "privatdemail.net",
  "proxymail.eu",
  "prtnx.com",
  "punkass.com",
  "putthisinyourspamdatabase.com",
  // ⚠ qq.com REMOVED — Tencent QQ Mail is the most popular Chinese
  //   email provider with hundreds of millions of legitimate users.
  //   Including it here would lock out a huge real-user population.
  "quickinbox.com",
  "rcpt.at",
  "reallymymail.com",
  "recode.me",
  "recursor.net",
  "regbypass.com",
  // ⚠ regbypass.comsafe-mail.net REMOVED — malformed domain (concat).
  "rejectmail.com",
  "reliable-mail.com",
  "rhyta.com",
  "rmqkr.net",
  "rppkn.com",
  "rtrtr.com",
  "s0ny.net",
  // ⚠ safe-mail.net REMOVED — legitimate encrypted email service.
  "safersignup.de",
  "safetymail.info",
  "safetypost.de",
  "sandelf.de",
  "saynotospams.com",
  "schafmail.de",
  "schrott-email.de",
  "secretemail.de",
  "secure-mail.biz",
  "selfdestructingmail.com",
  "selfdestructingmail.org",
  "sendspamhere.com",
  "shieldedmail.com",
  "shiftmail.com",
  "shortmail.net",
  "sibmail.com",
  "sinnlos-mail.de",
  "skeefmail.com",
  "slapsfromlastnight.com",
  "slaskpost.se",
  "smashmail.de",
  "smellfear.com",
  "snakemail.com",
  "snapmail.cc",
  "snkmail.com",
  "sofimail.com",
  "sofort-mail.de",
  "sogetthis.com",
  "soodonims.com",
  "spam.la",
  "spam.su",
  "spamavert.com",
  "spambob.com",
  "spambob.net",
  "spambob.org",
  "spambog.de",
  "spambog.ru",
  "spambox.info",
  "spambox.irishspringrealty.com",
  "spambox.us",
  "spamcannon.com",
  "spamcannon.net",
  "spamcero.com",
  "spamcorptastic.com",
  "spamcowboy.com",
  "spamcowboy.net",
  "spamcowboy.org",
  "spamday.com",
  "spamex.com",
  "spamfree.eu",
  "spamfree24.com",
  "spamfree24.de",
  "spamfree24.eu",
  "spamfree24.info",
  "spamfree24.net",
  "spamfree24.org",
  "spamgoes.in",
  "spamherelots.com",
  "spamhereplease.com",
  "spamhole.com",
  "spamify.com",
  "spaminator.de",
  "spamkill.info",
  "spaml.com",
  "spaml.de",
  "spammotel.com",
  "spamobox.com",
  "spamoff.de",
  "spamslicer.com",
  "spamspot.com",
  "spamthis.co.uk",
  "spamthisplease.com",
  "spamtroll.net",
  "speed.1s.fr",
  "supergreatmail.com",
  "supermailer.jp",
  "superrito.com",
  "suremail.info",
  "tagyourself.com",
  "talkinator.com",
  "teewars.org",
  "teleworm.com",
  "teleworm.us",
  "temp.emeraldwebmail.com",
  "temp.headstrong.de",
  "tempalias.com",
  "tempe-mail.com",
  "tempemail.biz",
  "tempemail.com",
  "tempemail.net",
  "tempinbox.co.uk",
  "tempinbox.com",
  "tempmail.eu",
  "tempmaildemand.com",
  "tempmailer.com",
  "tempmailer.de",
  "tempomail.fr",
  "temporarily.de",
  "temporarioemail.com.br",
  "temporaryemail.net",
  "temporaryforwarding.com",
  "temporaryinbox.com",
  "temporarymailaddress.com",
  "tempthe.net",
  "thanksnospam.info",
  "thankyou2010.com",
  "thecloudindex.com",
  "thisisnotmyrealemail.com",
  "thismail.net",
  "throwawayemailaddress.com",
  "tilien.com",
  "tittbit.in",
  "tizi.com",
  "tmailinator.com",
  "toomail.biz",
  "topranklist.de",
  "tradermail.info",
  "trash-amil.com",
  "trash-mail.at",
  "trash-mail.com",
  "trash-mail.de",
  "trash2009.com",
  "trashdevil.com",
  "trashemail.de",
  "trashmail.at",
  "trashmail.me",
  "trashmail.net",
  "trashmailer.com",
  "trashymail.net",
  "trialmail.de",
  "trillianpro.com",
  "twinmail.de",
  "tyldd.com",
  "uggsrock.com",
  "umail.net",
  "uplipht.com",
  "venompen.com",
  "veryrealemail.com",
  "viditag.com",
  "viralplays.com",
  "vpn.st",
  "vsimcard.com",
  "vubby.com",
  "wasteland.rfc822.org",
  "webemail.me",
  "weg-werf-email.de",
  "wegwerfadresse.de",
  "wegwerf-email-addressen.de",
  "wegwerf-emails.de",
  "wegwerfemailadresse.com",
  "wegwerfmail.info",
  "wegwerpmailadres.nl",
  "wetrainbayarea.com",
  "wetrainbayarea.org",
  "wh4f.org",
  "whatiaas.com",
  "whatpaas.com",
  "whatsaas.com",
  "whopy.com",
  "willhackforfood.biz",
  "willselfdestruct.com",
  "winemaven.info",
  "wronghead.com",
  "wuzup.net",
  "wuzupmail.net",
  // ⚠ www.* prefixed entries REMOVED — not valid email domain forms.
  "wwwnew.eu",
  "x.ip6.li",
  "xagloo.com",
  "xemaps.com",
  "xents.com",
  "xmaily.com",
  "xoxy.net",
  "yep.it",
  "yogamaven.com",
  "yopmail.fr",
  "yopmail.net",
  "ypmail.webarnak.fr.eu.org",
  "yuurok.com",
  "z1p.biz",
  "za.com",
  "zehnminuten.de",
  "zehnminutenmail.de",
  "zetmail.com",
  "zippymail.info",
  "zoaxe.com",
  "zoemail.net",
  "zomg.info",
  "zxcv.com",
  "zxcvbnm.com",
  "zzz.com",
]);

// ─────────────────────────────────────────────────────────────────────────────
// isDisposableEmail
// ─────────────────────────────────────────────────────────────────────────────
//
// Returns true if the email address belongs to a known disposable /
// temporary email service.
//
// Subdomain handling:
//   Some services hand out unique subdomains per inbox
//   (e.g. `inbox@user-foo.mailinator.com`). We progressively trim leading
//   labels and re-check, so `user-foo.mailinator.com` matches `mailinator.com`
//   in the set. We stop at the second-to-last label to avoid false positives
//   on ".com" / ".org" alone.
//
// Inputs:
//   email — assumed already lowercased + trimmed by caller (B24 normalization
//           is applied before this is called in /auth/register).
//
// Returns:
//   true  → block this signup
//   false → allow (not in our blocklist)
//
// Performance: O(k) where k is the number of dots in the domain (typically 1–3).
// Set lookup is O(1).
export function isDisposableEmail(email: string): boolean {
  if (!email || typeof email !== "string") return false;
  const at = email.lastIndexOf("@");
  if (at <= 0 || at === email.length - 1) return false;
  const domain = email.slice(at + 1).toLowerCase().trim();
  if (!domain) return false;

  // Direct match first (fast path — covers the vast majority of cases).
  if (DISPOSABLE_EMAIL_DOMAINS.has(domain)) return true;

  // Subdomain match: progressively peel leading labels and re-check.
  // Stop when only 2 labels remain (e.g. "mailinator.com") — never check
  // bare TLDs like "com" or "co.uk".
  const parts = domain.split(".");
  for (let i = 1; i < parts.length - 1; i++) {
    const candidate = parts.slice(i).join(".");
    if (DISPOSABLE_EMAIL_DOMAINS.has(candidate)) return true;
  }

  return false;
}
