// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-redesign/BoldEditorial.tsx": () => import("../components/mockups/landing-redesign/BoldEditorial.tsx"),
  "./components/mockups/landing-redesign/CinematicDark.tsx": () => import("../components/mockups/landing-redesign/CinematicDark.tsx"),
  "./components/mockups/landing-redesign/GlassmorphicPremium.tsx": () => import("../components/mockups/landing-redesign/GlassmorphicPremium.tsx")
};
